language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script: nosetests
before_script:
  - mysql -e 'create database mysql2pgsql;'
  - psql -c 'create database mysql2pgsql;' -U postgres
env:
  - DB=mysql
  - DB=postgres
branches:
  only:
    - master
    - develop
notifications:
  email:
    - philipsoutham@gmail.com